#ifndef FASTLED_CONFIG_H
#define FASTLED_CONFIG_H

// Core FastLED Configuration
#define FASTLED_INTERNAL
#define FASTLED_ESP32_SPI_BUS FSPI
#define FASTLED_ESP32_SPI_CLOCK_DIVIDER 8
#define FASTLED_ALL_PINS_HARDWARE_SPI
#define FASTLED_ALLOW_INTERRUPTS 0

// Visual Cortex specific LED configurations
#define VISUAL_CORTEX_MAX_BRIGHTNESS 255
#define VISUAL_CORTEX_DEFAULT_FPS 60
#define VISUAL_CORTEX_COLOR_CORRECTION TypicalLEDStrip

#endif 